export { ServicesHeroSection } from './ServicesHeroSection';
export { ServicesMainSection } from './ServicesMainSection';
export { WorkProcessSection } from './WorkProcessSection';
export { DifferentialSection } from './DifferentialSection';
export { ProjectsSection } from './ProjectsSection';
export { QualityCareSection } from './QualityCareSection';
export { TrainingMentoringSection } from './TrainingMentoringSection';
export { TrackingEvolutionSection } from './TrackingEvolutionSection';
export { InvolvementSection } from './InvolvementSection';
